### ISSUE TITLE
keeping the repo up to date

### ISSUE THREAD

**Issue by OlivierJM** [BongoHive/react-2#7]
@alfeyo @Joebbrien if you have time kindly take a look at a few merge requests from dependantbot and merge them to keep the repo updated if it is still being used for the internship, you can also archive it if no longer in user. 

alternatively since it is open source, I can keep it update but let me know what you think.

**Comment by alfeyo** [comment]
@OlivierJM I agree with you to keep this up to date and open source, I have gone ahead and merge pull requests from the Dependabot I have also cloned the repo to update the lock file. 

Please advise on what else need's to be done.

**Comment by OlivierJM** [comment]
> @OlivierJM I agree with you to keep this up to date and open source, I have gone ahead and merge pull requests from the Dependabot I have also cloned the repo to update the lock file.
> 
> Please advise on what else need's to be done.

Thanks for that @alfeyo, I think that will do for now.

I am curious, are you still using this for the internship ? should we add more functionality requirement ?

**Comment by alfeyo** [comment]
Yes we we are still using this for the internship adding in more functionality requirements would be very much appreciated.

**Comment by OlivierJM** [comment]
> Yes we we are still using this for the internship adding in more functionality requirements would be very much appreciated.

awesome.
